theme: jekyll-theme-slate

title: myCustomTitle
description: myCustomAndDetailedDescription

plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: true
  
include:
  - README.md
