theme: jekyll-theme-slate

# _config.yml adapted from advanced-data-wrangle, an adaption of workshop-template-b, evanwill
# https://github.com/GriffithUniLibrary/Advanced-data-wrangle and https://github.com/evanwill/workshop-template-b
# Applying a bit of control to the Jekyll template 

# Site settings
# title appears in the header
title: Digital Dexterity
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Font Awesome 5 free, https://fontawesome.com/icons?d=gallery&m=free
# some options: fas fa-wrench; fas fa-cogs; fas fa-code; fas fa-chalkboard-teacher; fas fa-book-open

# description and keywords for meta tags
description: Home of the Digital Dexterity self assessment tool<br /> created by the Griffith University Library.
keywords: "Digital Dexterity, digital literacy self assessment"

# add the full url for the github repository
repo: "https://griffithunilibrary.github.io/digital-dexterity/"

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: G-NC3PPY2JZB



plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: true
  
include:
  - README.md


