theme: jekyll-theme-slate

title: Digital Dexterity
description: Home of the Digital Dexterity self assessment tool created by the Griffith University Library.

plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: true
  
include:
  - README.md
